### PR TITLE
Directory Changed

### PR DESCRIPTION
**Pull request by RajaSudharshan**
Directory Changed Now! @1-Harshit @chirag9127

### CODE REVIEW

**Comment by chirag9127** [comment]
@RajaSudharshan can you add a requirements.txt file?

**Comment by chirag9127** [comment]
@RajaSudharshan The future aspects, risks and tokenomics pages are not connected to the uniswap analysis page.

**Comment by chirag9127** [comment]
image
The coingecko api requests are not working. Can you add a readme on how to get them to work?

**Comment by RajaSudharshan** [comment]
I have informed the issue of api towards Swapnali and the issue is because
the trial exceeded.And other changes i will resolve and update you soon.

**Pull request merged**
