### PR TITLE
Vinay Parampalli | Injective

### PR DESCRIPTION
**Pull request by VINAY1072**
@encrypted-soul 
@chirag9127

### CODE REVIEW

**Comment by encrypted-soul** [comment]
Can you add requirements.txt @VINAY1072

**Comment by VINAY1072** [comment]
added requirements.txt

**Comment by VINAY1072** [comment]
@encrypted-soul Sir, Is our submission currently under review?

**Comment by 1-Harshit** [comment]
Hey @VINAY1072 
Thanks for adding requirements. You submission is under evaluation interally. Will host for voting soon.
Cheers

**Pull request merged**
