### PR TITLE
Shrirang Savale | GNOSIS

### PR DESCRIPTION
**Pull request by Whitehatdown**
@encrypted-soul @chirag9127 This is a submission for the blaze AI hackathon by Shrirang Savale (Team Leader) and Uday Joshi representing Indian Institute of Information Technology, Nagpur. 

Link : https://whitehatdown-streamlit-example-streamlit-app-jnjyzu.streamlit.app/

The above is the link to a working sample of StreamLit App...

### CODE REVIEW

**Comment by Whitehatdown** [comment]
@encrypted-soul @chirag9127

**Comment by Whitehatdown** [comment]
@1-Harshit The incorrect directory problem has been solved since last 3 days. I request you to evaluate our submission...

**Comment by Whitehatdown** [comment]
@chirag9127 @encrypted-soul Please review this pull request...

**Comment by 1-Harshit** [comment]
Merged manually

**Pull request closed without merging**
