### PR TITLE
Kalpit | Injective

### PR DESCRIPTION
**Pull request by Kalpitadhao77**
@chirag9127 @encrypted-soul

### CODE REVIEW

**Comment by Kalpitadhao77** [comment]
> @chirag9127 @encrypted-soul

My Deployed Streamlit App - [](https://blazequant.streamlit.app/)

**Comment by 1-Harshit** [comment]
Hey @Kalpitadhao77 
I can see you seem to be using yfinance. We cannot accept this submission as this is not a educational project. Please change the data source. Thanks!

> It's an open-source tool that uses Yahoo's publicly available APIs, and is intended for research and educational purposes.
> 
> You should refer to Yahoo!'s terms of use ([here](https://policies.yahoo.com/us/en/yahoo/terms/product-atos/apiforydn/index.htm), [here](https://legal.yahoo.com/us/en/yahoo/terms/otos/index.html), and [here](https://policies.yahoo.com/us/en/yahoo/terms/index.htm)) for details on your rights to use the actual data downloaded. Remember - the Yahoo! finance API is intended for personal use only.

**Comment by Kalpitadhao77** [comment]
> Hey @Kalpitadhao77 I can see you seem to be using yfinance. We cannot accept this submission as this is not a educational project. Please change the data source. Thanks!
> 
> > It's an open-source tool that uses Yahoo's publicly available APIs, and is intended for research and educational purposes.
> > You should refer to Yahoo!'s terms of use ([here](https://policies.yahoo.com/us/en/yahoo/terms/product-atos/apiforydn/index.htm), [here](https://legal.yahoo.com/us/en/yahoo/terms/otos/index.html), and [here](https://policies.yahoo.com/us/en/yahoo/terms/index.htm)) for details on your rights to use the actual data downloaded. Remember - the Yahoo! finance API is intended for personal use only.

Hey @1-Harshit 

There weren't any specified details mentioned previously about data retrieval and anyways  I am fetching real time data from yfinance
My code is heavily integrated with yfinance and changing the data source would be quite difficult and would take a significant time as you can see it is over 900 lines of code with a high usage of yfinance data for providing insights and results.

I request you to consider my pull request as I have already spent too many hours on building this app and I don't want it to go to waste.

**Comment by 1-Harshit** [comment]
@Kalpitadhao77 
Could you share details of your development environment? We're not able to setup your dependencies. This is the error message. 
ERROR: No matching distribution found for vectorbt==0.25.1

**Comment by Kalpitadhao77** [comment]
> @Kalpitadhao77 Could you share details of your development environment? We're not able to setup your dependencies. This is the error message. ERROR: No matching distribution found for vectorbt==0.25.1

Hi @1-Harshit , I just tried it, it's working for me.
instead of vectorbt==0.25.1, try setting up just vectorbt, maybe that will solve the issue

**Comment by 1-Harshit** [comment]
I've already tried that, can you share your dev enviroment? Stuff like python version, pip version, OS, and anything else you might find relevant.

**Comment by Kalpitadhao77** [comment]
> I've already tried that, can you share your dev enviroment? Stuff like python version, pip version, OS, and anything else you might find relevant.

Python 3.8.16 
pip 23.0.1
notebook : 6.5.3

**Pull request merged**
